<a href="https://colab.research.google.com/github/jym1028z/aipython/blob/main/251107.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1. 왜 파이썬 리스트 대신 넘파이를 사용할까요? (Why NumPy?)**

pip list로 저장된 거 확인 가능

In [11]:
import numpy as np
import time
# 1. 파이썬 리스트를 사용한 경우
my_list = list(range(1_000_000))
start_time = time.time()
result_list = [x * 2 for x in my_list]
end_time = time.time()
print(f"파이썬 리스트 실행 시간: {end_time - start_time:.5f}초")
# 2. 넘파이 배열을 사용한 경우
my_array = np.arange(1_000_000)
start_time = time.time()
result_array = my_array * 2
end_time = time.time()
print(f"넘파이 배열 실행 시간: {end_time - start_time:.5f}초")

파이썬 리스트 실행 시간: 0.05490초
넘파이 배열 실행 시간: 0.00169초


#**3. 넘파이의 핵심: 배열(ndarray) 만들기 (Creating Arrays)**

In [12]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [13]:
type(a)

numpy.ndarray

#**4. 넘파이의 마법: 간결한 배열 연산 (The Magic of NumPy Operations)**

In [14]:
a = np.array([1, 2, 3, 4, 5])
# 배열의 모든 요소에 10 더하기
print(a + 10)
# 배열의 모든 요소에 2 곱하기
print(a * 2)

[11 12 13 14 15]
[ 2  4  6  8 10]


In [15]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
# 배열끼리 덧셈 (10+1, 20+2, 30+3)
print(arr1 + arr2)

[11 22 33]


#**5.3. 조건에 맞는 데이터만 고르기 (Boolean Indexing)**

In [17]:
a = np.array([10, 20, 30, 40, 50])
# 배열 a의 요소 중 25보다 큰 값만 선택
condition_mask = (a > 25) # 1단계: 불리언 마스크 생성
filtered_array = a[condition_mask] # 2단계: 마스크를 사용해 데이터 필터링
print(filtered_array)

[30 40 50]


#**6.2. 배열의 형태 바꾸기: **.reshape()****

In [ ]:
# 이런 것이 있구나 정도만

#**7. 실전 예제: 드론 배터리 소모량 예측하기**

In [18]:
import numpy as np

distances = np.array([1, 2, 3, 5, 8])
windspeeds = np.array([0, 5, 10, 7, 12])

base_usage_rate = 10
additional_usage_rate = windspeeds

total_usage_rate = base_usage_rate + additional_usage_rate
battery_consumption = distances * total_usage_rate

print("비행 거리 (km):", distances)
print("풍속 (m/s):", windspeeds)
print("총 소모율 (%/km):", total_usage_rate)
print("예상 배터리 소모량 (%):", battery_consumption)

비행 거리 (km): [1 2 3 5 8]
풍속 (m/s): [ 0  5 10  7 12]
총 소모율 (%/km): [10 15 20 17 22]
예상 배터리 소모량 (%): [ 10  30  60  85 176]


#**1. 판다스(Pandas)와 데이터프레임의 이해**

student_data = {
'name': ['Kim', 'Lee', 'Park'],
'test': [85, 92, 78],
'assign1': [88, 95, 80],
'assign2': [91, 89, 82]
}

: attribure 4개임

In [24]:
import pandas as pd

# CSV 파일 경로를 입력해주세요.
# 예시: df = pd.read_csv('파일경로/파일이름.csv')
# 현재 디렉토리에 'Iris.csv' 파일이 있으니, 이 파일을 사용해 볼게요.

df = pd.read_csv('Iris.csv')
print("CSV 파일을 성공적으로 불러왔습니다.")
display(df.tail(10))

print(df['Id'])

CSV 파일을 성공적으로 불러왔습니다.


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

0        1
1        2
2        3
3        4
4        5
      ... 
145    146
146    147
147    148
148    149
149    150
Name: Id, Length: 150, dtype: int64


#**4.2. 비교 연산을 통한 조건부 데이터 필터링**

In [28]:
minisepal=df[df['SepalLengthCm']<5]
display(minisepal)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
6      7            4.6           3.4            1.4           0.3   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            4.3           3.0            1.1           0.1   
22    23            4.6           3.6            1.0           0.2   
24    25            4.8           3.4            1.9           0.2   
29    30            4.7           3.2            1.6           0.2   
30    31            4.8           3.1            1.6           0.2   
34    35            4.9           3.1            1.5           0.1   
37    38            4.9           3.1            1.5           0.1   
38    39            4.4           3.0            1.3           0.2   
41    42            4.5           2.3            1.3           0.3   
42    43            4.4           3.2            1.3           0.2   
45    46            4.8           3.0            1.4           0.3   
47    48            4.6           3.2            1.4           0.2   
57    58            4.9           2.4            3.3           1.0   
106  107            4.9           2.5            4.5           1.7   

             Species  
1        Iris-setosa  
2        Iris-setosa  
3        Iris-setosa  
6        Iris-setosa  
8        Iris-setosa  
9        Iris-setosa  
11       Iris-setosa  
12       Iris-setosa  
13       Iris-setosa  
22       Iris-setosa  
24       Iris-setosa  
29       Iris-setosa  
30       Iris-setosa  
34       Iris-setosa  
37       Iris-setosa  
38       Iris-setosa  
41       Iris-setosa  
42       Iris-setosa  
45       Iris-setosa  
47       Iris-setosa  
57   Iris-versicolor  
106   Iris-virginica

In [29]:
minisepal['SepalLengthCm']

1      4.9
2      4.7
3      4.6
6      4.6
8      4.4
9      4.9
11     4.8
12     4.8
13     4.3
22     4.6
24     4.8
29     4.7
30     4.8
34     4.9
37     4.9
38     4.4
41     4.5
42     4.4
45     4.8
47     4.6
57     4.9
106    4.9
Name: SepalLengthCm, dtype: float64